version: '3.8'

services:
  salary-predictor:
    build: .
    image: salary-predictor-image
    container_name: salary-predictor-container
    volumes:
      - .:/app
      - ./models:/app/models
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    ports:
      - "${JUPYTER_PORT:-8888}:${JUPYTER_PORT:-8888}" # Jupyter Notebook
    environment:
      - PYTHONPATH=/app
      - JUPYTER_PORT=${JUPYTER_PORT:-8888}
    # Override the default entrypoint to keep the container running
    # for development purposes
    entrypoint: ["tail", "-f", "/dev/null"]